### ISSUE TITLE
Request for Video Generation Inference Script

### ISSUE THREAD

**Issue by ltzheng** [mit-han-lab/vila-u#1]
Thanks for the great work! Do you have any inference script available for video generation? If not, are there plans to release it in the future?

**Comment by ltzheng** [comment]
Also, the `process_image_video` in `vila_u/data/dataset.py` is missing.

**Comment by zhuoyang20** [comment]
Hi @ltzheng,

Thank you for your interest! I've added video generation inference. Here's an example command:

```bash
CUDA_VISIBLE_DEVICES=0 python inference.py --model_path path/to/your_downloaded_model --prompt "Fireworks in the air." --video_generation True --save_path path/to/save_videos
```

The problem of `process_image_video` is also fixed. Please feel free to reach out if you have additional questions.

Best,
Zhuoyang

**Comment by ltzheng** [comment]
Thank you for your quick response! The text2video command works. I suppose that vila-u might also support image2video and image2image generation. Are there commands available for these? In my opinion it's essentially a variation of text2video, where the input image serves as the initial frame.

**Comment by zhuoyang20** [comment]
Currently, we have not yet incorporated image2video and image2image data into the training process, which may impact performance on these tasks. For image2video, I think you can try to provide the initial frame to generate the next few frames. Additionally, if you have customized data, you can easily fine-tune VILA-U, as our framework tokenizes all inputs.

**Comment by ltzheng** [comment]
Thanks! Closing this issue now.
