### ISSUE TITLE
The version of lmms-eval version?

### ISSUE THREAD

**Issue by hqhQAQ** [mit-han-lab/vila-u#10]
Thanks for your excellent work!
I am wondering the lmms-eval version used here, since the updates for this package are very frequent.

**Comment by hqhQAQ** [comment]
I have figured out that the version of lmms_eval is 0.1.0.

**Comment by zhuoyang20** [comment]
Hi @hqhQAQ,

You can always use the latest version of lmms_eval.

```
pip install git+https://github.com/EvolvingLMMs-Lab/lmms-eval.git --upgrade
```

Best,
Zhuoyang
